# Generated by Django 4.0.4 on 2022-04-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blinks',
            new_name='blinkapp_blinks',
        ),
    ]
