# Generated by Django 4.0.4 on 2022-04-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0002_rename_blinks_blinkapp_blinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='blinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('blink_count', models.IntegerField()),
                ('drowsy_dur', models.IntegerField()),
                ('comp_dur', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='blinkapp_blinks',
        ),
    ]
