# Generated by Django 4.0.4 on 2022-04-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0003_blinks_delete_blinkapp_blinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blinks',
            name='blink_count',
        ),
        migrations.RemoveField(
            model_name='blinks',
            name='comp_dur',
        ),
        migrations.RemoveField(
            model_name='blinks',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blinks',
            name='drowsy_dur',
        ),
        migrations.RemoveField(
            model_name='blinks',
            name='time',
        ),
    ]
