# Generated by Django 4.0.4 on 2022-04-20 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blinks',
        ),
    ]
