# Generated by Django 4.0.4 on 2022-04-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0008_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blnk',
            table='blnk',
        ),
    ]
