# Generated by Django 4.0.4 on 2022-04-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0009_alter_blnk_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blnk',
            name='date',
        ),
    ]
