# Generated by Django 4.0.4 on 2022-04-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0010_remove_blnk_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blnk',
            old_name='blink_count',
            new_name='blink_cnt',
        ),
        migrations.RenameField(
            model_name='blnk',
            old_name='comp_dur',
            new_name='comp_cnt',
        ),
        migrations.RenameField(
            model_name='blnk',
            old_name='drowsy_dur',
            new_name='drowsy_cnt',
        ),
    ]
