# Generated by Django 4.0.4 on 2022-04-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0011_rename_blink_count_blnk_blink_cnt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blnk',
            old_name='comp_cnt',
            new_name='strain_cnt',
        ),
    ]
