# Generated by Django 4.0.4 on 2022-04-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0012_rename_comp_cnt_blnk_strain_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blnk',
            name='blink_cnt',
        ),
        migrations.RemoveField(
            model_name='blnk',
            name='drowsy_cnt',
        ),
        migrations.RemoveField(
            model_name='blnk',
            name='strain_cnt',
        ),
        migrations.RemoveField(
            model_name='blnk',
            name='time',
        ),
        migrations.AlterModelTable(
            name='blnk',
            table=None,
        ),
    ]
