# Generated by Django 4.0.4 on 2022-04-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0013_remove_blnk_blink_cnt_remove_blnk_drowsy_cnt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blnk',
        ),
    ]
