# Generated by Django 4.0.4 on 2022-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blinkapp', '0014_delete_blnk'),
    ]

    operations = [
        migrations.CreateModel(
            name='blnk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('time', models.TimeField(auto_now=True)),
                ('blink_cnt', models.IntegerField()),
                ('drowsy_cnt', models.IntegerField()),
                ('strain_cnt', models.IntegerField()),
            ],
            options={
                'db_table': 'blnk',
            },
        ),
    ]
