# Generated by Django 4.0.4 on 2022-04-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blinkapp', '0015_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blnk',
        ),
    ]
