# Generated by Django 4.0.4 on 2022-05-03 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlinkCapture',
            fields=[
                ('blink_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('blink_cnt', models.IntegerField()),
                ('blink_rate', models.IntegerField()),
                ('strain_cnt', models.IntegerField()),
                ('drowsy_cnt', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blink_capture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'blink_id')},
            },
        ),
    ]
